server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/task_user_service
    username: root
    password: System@15
    driver-class-name: com.mysql.cj.jdbc.Driver
